param([Parameter(ValueFromRemainingArguments=$true)][string[]]$_args)
$p = ''
$sessionFlag = ''
$extraFlags = ''
for ($i = 0; $i -lt $_args.Count; $i++) {
    switch ($_args[$i]) {
        '-p'             { $p = $_args[++$i] }
        '--name'         { $extraFlags += " --name `"$($_args[++$i])`"" }
        '--resume'       {
            if (($i + 1) -lt $_args.Count -and -not $_args[$i+1].StartsWith('--')) {
                $sessionFlag = "--resume `"$($_args[++$i])`""
            } else {
                $sessionFlag = '--resume'
            }
        }
        '--continue'     { $sessionFlag = '--continue' }
        '--fork-session' { $extraFlags += ' --fork-session' }
        '--worktree'     {
            if (($i + 1) -lt $_args.Count -and -not $_args[$i+1].StartsWith('--')) {
                $extraFlags += " --worktree `"$($_args[++$i])`""
            } else {
                $extraFlags += ' --worktree'
            }
        }
    }
}
# Generated by ClaudeManager
# Usage: .\script.ps1 [-p prompt]
#   -p  프롬프트
# ----------
# ----------
$env:CLAUDE_CODE_USE_POWERSHELL_TOOL = '1'

# ----------
if ($sessionFlag) { $sessionFlag = $sessionFlag.Trim() -split '\s+' } else { $sessionFlag = @() }
if ($extraFlags.Trim()) { $extraFlags = $extraFlags.Trim() -split '\s+' } else { $extraFlags = @() }
if ($p) { $p = @($p) } else { $p = @() }

& claude `
    --dangerously-skip-permissions `
    @sessionFlag `
    @extraFlags `
    @p
